### PR TITLE
Upgrade to BaseX v11

### LINKED ISSUE #25: Make sure TAPAS-xq runs in BaseX 11
The [newest version of BaseX](https://basex.org/2024/06/06/basex-11.0-the-xmlprague-2024-edition/) revised the names and parameters of some long-standing functions, and adjusted some configuration options. I'll need to check TAPAS-xq code against the [changelog](https://docs.basex.org/main/Changelog), and update the Docker container to use BaseX 11 instead of 10.

### PR DESCRIPTION
**Pull request by amclark42**
Resolves #25.

It turns out that the upgrade to BaseX v11 is pretty seamless! All endpoints have been tested for deprecations. The configuration settings and the BaseX-specific functions can remain unchanged.

This pull request does include slight improvements to the documentation and code:

- The BaseX "Queries" tab in the Database Administration app has been renamed to "Editor", reflecting the v11 change.
- Additional context has been added in the Readme for "EXPath application XARs", and why we continue to use the package descriptor.
- The "Update view packages" endpoint is now clearer in its response when the user doesn't have permission to make the update (admin permissions are required). The documentation has been updated to stress this point.
- The GitHub URL to `tapas-api.xql` has been updated to the `develop` branch.

Unfortunately, BaseX v11.0 includes what appears to be a bug in the `inspect:xqdoc()` function: Each `<xqdoc:description>` now contains a very large number rather than the main content of the XQDoc comment. This PR will remain in draft form until I can determine if there's a workaround, or if we should wait for v11.1.

To complete this PR:

- [x] Test all API endpoints
- [x] Restore the readability of the "Get documentation" endpoint
- [x] Update TAPAS-xq version
- [x] Update which BaseX versions can be used
- [x] Use BaseX v11 to construct Docker image and container

### CODE REVIEW

**Comment by amclark42** [comment]
The `inspect:xqdoc()` bug has been fixed in the BaseX v11.1 beta!

To allow BaseX v11.0 to be used, I've added fallback behavior: If the first `<xqdoc:description>` has no whitespace in it, TAPAS-xq considers the content unusable. Instead, a call to the API documentation endpoint will return the pre-generated HTML or Markdown saved to this repository.

**Comment by amclark42** [comment]
BaseX v11.1 just came out, so I’ve updated the Docker image to use that! I can confirm that the API documentation is being dynamically generated from the source code once more (check the timestamp at the top).

The new version has changed the HTTP server port from 8080 to 80. However, nothing should appear different if you’re using the Docker container to run TAPAS-xq. I’ve adjusted the Dockerfile to use 8080 no matter what.

**Review by candyhazlett — APPROVED** [review]
After updating my local Docker image, all three HTTP requests made:

- **POST** via [store-core-file-and-supplementals](https://github.com/NEU-DSG/tapas-xq/blob/develop/API.md#store-core-file-and-supplementals):
  1. add a new core file
  2. replace newly added core file with updated version of the file
- **GET**: [read-core-file](https://github.com/NEU-DSG/tapas-xq/blob/develop/API.md#read-core-file)
- **DELETE**: [delete-core-file](https://github.com/NEU-DSG/tapas-xq/blob/develop/API.md#delete-core-file)

were handled correctly and returned the response codes outlined in the README. This PR should be ready to merge. 

Unrelated to the PR, I would love to see an `updated_at` column added to the db admin dashboard [page](http://localhost:8080/dba/database?name=tapas-data) for the Tapas db data. Those date values are helpful for testing.

**Comment by amclark42** [comment]
Thanks so much, @candyhazlett!

I agree; having timestamps would be handy. We can’t do anything about BaseX’s database app, but that’s an excellent idea for new administrator-oriented API endpoint. 🤔 I’ll add a issue.

**Pull request merged**
